name: qrmaker
description: "Create QR Code of text and UPI."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^7.3.1
  google_fonts: ^6.2.1
  pretty_qr_code: ^3.3.0
  screenshot: ^3.0.0
  image_gallery_saver: ^2.0.3
  fluttertoast: ^8.2.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
